export const en = {
  metadata: {
    title: "Custom AI Operators | unda",
    description: "AI operators shaped around your processes, rules, systems and boundaries.",
  },
  site: {
    homeLabel: "custom.unda.ai home",
    currentLanguage: "Current language: English",
    primaryNavigationLabel: "Primary navigation",
    mobileNavigationLabel: "Mobile navigation",
    mobilePrimaryNavigationLabel: "Mobile primary navigation",
    footerNavigationLabel: "Footer navigation",
    menuOpen: "MENU",
    menuClose: "CLOSE",
    mobileTagline: "CUSTOM AI OPERATORS",
    primaryNavigation: [
      { label: "Solutions", href: "#operator-profiles" },
      { label: "Social Operator", href: "https://social.unda.ai", external: true },
      { label: "Start a Project", href: "#operator-intake", emphasis: true },
    ],
    footerGroups: [
      {
        title: "CUSTOM",
        links: [
          { label: "Solutions", href: "#operator-profiles" },
          { label: "Start a Project", href: "#operator-intake", emphasis: true },
        ],
      },
      {
        title: "PRODUCTS",
        links: [
          { label: "Social Operator", href: "https://social.unda.ai", external: true },
        ],
      },
      {
        title: "ECOSYSTEM",
        links: [
          { label: "unda.ai", href: "https://unda.ai", external: true },
          { label: "theasylum.agency", href: "https://theasylum.agency", external: true },
        ],
      },
      {
        title: "LEGAL",
        links: [
          { label: "Privacy", href: "/privacy" },
          { label: "Terms", href: "/terms" },
        ],
      },
    ],
    footerBrand: "Built around ",
    footerBrandHighlight: "real work.",
    footerCredit: "A project by ",
    footerCreditLink: "theasylum.agency",
    footerCopyright: "© 2026 unda.ai",
  },
  hero: {
    scrollCue: "Scroll",
    heroCopy: {
      eyebrow: "Custom AI Operators",
      headlineLines: ["You already know", "how your business", "should work."],
      headlineSansDesktop: ["We turn that knowledge", "into an AI operator", "built around you."],
      headlineSansMobile: ["We turn that", "knowledge into an", "AI operator", "built around you."],
      supportingCopy: "An operator shaped by your processes, rules and systems —\ndesigned to understand context, carry out defined work\nand operate within the boundaries you set.",
      microTitle: "Start with a process, problem or recurring task.",
      microcopy: "No technical brief required.",
    },
    heroActions: {
      primary: "Explore Your Operator",
      secondary: "See How Operators Work",
    },
    operatorArchitecture: {
      title: "Your Operator",
      ready: "Operator Ready",
      readySub: "Built around you",
    },
    knowledgeFragments: [
      { id: "approval", label: "APPROVAL REQUIRED", mobileLabel: "YOUR RULES", icon: "user", emphasis: true },
      { id: "history", label: "CHECK CUSTOMER HISTORY", icon: "database" },
      { id: "exceptions", label: "ESCALATE EXCEPTIONS", icon: "alert" },
      { id: "crm", label: "UPDATE CRM", icon: "edit" },
      { id: "policy", label: "RESPONSE POLICY 04", icon: "shield" },
      { id: "review", label: "MANAGER REVIEW", mobileLabel: "HUMAN APPROVAL", icon: "review" },
      { id: "action", label: "DEFINED ACTION", mobileLabel: "DEFINED ACTION", icon: "action" },
      { id: "decision", label: "HUMAN DECISION", icon: "decision" },
    ],
    operatorModules: [
      { id: "context", title: "CONTEXT", description: "Understands what’s happening" },
      { id: "rules", title: "RULES", description: "Knows what to do and what to avoid" },
      { id: "actions", title: "ACTIONS", description: "Carries out defined work" },
      { id: "boundaries", title: "BOUNDARIES", description: "Operates within limits you set" },
    ],
  },
  work: {
    workCopy: {
      eyebrow: "02 — THE WORK ALREADY EXISTS",
      headlineLead: "Most businesses do not need more software.",
      headlineClose: "They need the work they already do to run better.",
      supporting: "Requests, decisions, information and follow-ups already move through your business every day.",
      supportingClose: "The problem is not that the work does not exist. It is that too much of it still depends on memory, repetition and manual coordination.",
      closing: "This is where a custom operator begins.",
      closingSupport: "Built around the work your business already does — not around a generic AI tool.",
      closingAction: "Let’s talk about your business",
    },
    customerRequestSteps: [
      { id: "message", label: "New customer message", meta: "MESSAGE" },
      { id: "forward", label: "Forwarded to another chat", meta: "INTERNAL CHAT" },
      { id: "sheet", label: "Someone opens a spreadsheet", meta: "STOCK SHEET" },
      { id: "owner", label: "Someone asks the owner", meta: "APPROVAL" },
    ],
    reportSources: [
      { id: "sales", label: "Sales spreadsheet", value: "184 orders", kind: "sheet" },
      { id: "campaign", label: "Campaign results", value: "+12.4%", kind: "metric" },
      { id: "orders", label: "Orders list", value: "39 pending", kind: "list" },
      { id: "messages", label: "Customer messages", value: "67 open", kind: "messages" },
    ],
    decisionQuestions: [
      { id: "approve", label: "Can we approve this?", meta: "SALES · 11:26" },
      { id: "price", label: "Which price should I use?", meta: "ORDERS · 11:29" },
      { id: "client", label: "What should I tell the client?", meta: "SUPPORT · 11:31" },
      { id: "valid", label: "Is this still valid?", meta: "OPERATIONS · 11:34" },
    ],
    operatorFlow: ["REQUEST", "CHECK", "DECIDE", "RESPOND", "FOLLOW UP"],
    sceneLabels: [
      { id: "request", number: "01", label: "Customer request" },
      { id: "report", number: "02", label: "Weekly report" },
      { id: "decision", number: "03", label: "One person" },
      { id: "flow", number: "04", label: "Operator flow" },
      { id: "closing", number: "05", label: "Begin here" },
    ],
    scenes: {
      request: {
        label: "Customer request",
        title: "A simple question starts moving.",
        messageLabel: "NEW CUSTOMER MESSAGE",
        message: "Is this item available?",
        waitingLabel: "WAITING",
        waitingTitle: "Waiting for an answer",
        waitingMeta: "09:47 — Customer still waiting",
        mobileOutcome: "33 minutes. One unanswered question.",
      },
      report: {
        label: "Weekly report",
        title: "The report is assembled by hand.",
        time: "FRIDAY — 16:40",
        copiedManually: "COPIED MANUALLY",
        reportLabel: "WEEKLY REPORT",
        reportTitle: "One report",
        outdatedLabel: "OUTDATED BEFORE COMPLETION",
        outdatedTitle: "One number has already changed.",
        mobileOutcome: "Finished once. Rebuilt again.",
      },
      decision: {
        label: "The person everyone waits for",
        title: "The final answer lives in one place.",
        finalAnswer: "FINAL ANSWER",
        onePerson: "ONE PERSON",
        waiting: "WAITING FOR ONE PERSON",
        mobileOutcome: "Four questions. The same dependency.",
      },
      flow: {
        label: "From friction to flow",
        title: "The work stays familiar. The way it moves changes.",
        operatorLabel: "CUSTOM OPERATOR",
      },
      closing: "WHERE THE OPERATOR BEGINS",
    },
  },
  approach: {
    approachCopy: {
      eyebrow: "03 — WHEN RULES ARE NOT ENOUGH",
      headlineLead: "Rules work when every case looks the same.",
      headlineClose: "Real work rarely does.",
      transition: "That is where we begin.",
      resultLead: "The result is not another generic AI tool.",
      resultClose: "It is a clearly defined operational role, built specifically for your business.",
      finalLead: "We do not begin with AI.",
      finalClose: "We begin with the work.",
      cta: "Start with your workflow",
    },
    methodSteps: [
      {
        id: "find-friction",
        number: "01",
        label: "FIND THE FRICTION",
        title: "We find where the work breaks",
        body: "We look for the moments where tasks slow down, information gets lost, the same action is repeated or everything returns to one person for a decision.",
        visualLabel: "A workflow interrupted by repeated tasks, waiting and missing context.",
      },
      {
        id: "choose-approach",
        number: "02",
        label: "CHOOSE THE APPROACH",
        title: "We choose the right kind of solution",
        body: "Not every problem needs an AI operator. Sometimes a clearer rule is enough. Sometimes conventional automation is the right answer. And sometimes the work needs a system that can understand context, handle variation and know when to ask for help.",
        visualLabel: "Three valid paths: a rule, conventional automation or a custom operator.",
      },
      {
        id: "define-role",
        number: "03",
        label: "DEFINE THE ROLE",
        title: "We define the operator’s role",
        body: "Together, we decide what the operator should know, what it can access, what actions it may take and which decisions must remain with a person.",
        visualLabel: "A defined operational role bounded by knowledge, access, actions and limits.",
      },
      {
        id: "build-operator",
        number: "04",
        label: "BUILD AROUND THE BUSINESS",
        title: "We build it around your business",
        body: "We connect the relevant tools and information, test the operator on real situations and refine how it works until it fits the way your business actually operates.",
        visualLabel: "An operational role connected to existing business tools and human review.",
      },
    ],
    frictionSignals: [
      "REPEATED TASK",
      "WAITING",
      "MISSING CONTEXT",
      "MANUAL CHECK",
      "APPROVAL NEEDED",
    ],
    approachPaths: [
      { id: "rule", title: "RULE", description: "The action is always the same" },
      { id: "automation", title: "AUTOMATION", description: "The steps are known in advance" },
      { id: "operator", title: "CUSTOM OPERATOR", description: "Context and variation shape the action" },
    ],
    roleBoundaries: ["KNOWLEDGE", "ACCESS", "ACTIONS", "LIMITS"],
    businessSystems: ["INBOX", "SPREADSHEET", "CRM", "CALENDAR", "DOCUMENTS", "INTERNAL RULES"],
    roleDefinition: [
      ["RESPONSIBILITY", "Customer requests"],
      ["KNOWLEDGE", "Business context"],
      ["ACCESS", "Relevant systems"],
      ["ACTIONS", "Defined work"],
      ["BOUNDARIES", "Human review"],
    ],
    visuals: {
      friction: {
        enters: "WORK ENTERS",
        stops: "WORK STOPS",
        found: "FRICTION FOUND",
      },
      approach: {
        question: "WHAT DOES THE WORK ACTUALLY NEED?",
        note: "THE PROCESS DETERMINES THE APPROACH",
      },
      role: {
        definedRole: "DEFINED OPERATIONAL ROLE",
        operatorName: "CUSTOMER REQUEST\nOPERATOR",
        mayAct: "OPERATOR MAY ACT",
        humanDecides: "HUMAN DECIDES",
      },
      build: {
        operationalRole: "OPERATIONAL ROLE",
        customOperator: "CUSTOM OPERATOR",
        description: "Reads context · applies rules\nacts · asks when needed",
        note: "TESTED ON REAL WORK · REFINED IN CONTEXT",
      },
    },
  },
  operators: {
    operatorProfilesCopy: {
      eyebrow: "04 — WHAT AN OPERATOR CAN TAKE ON",
      headlineLead: "An operator does not need to run your whole business.",
      headlineClose: "It needs to take responsibility for the right part of it.",
      supporting: "Start with one clear area of work. Define what should keep moving, what the operator can handle and when a person should step in.",
      closingLead: "Different businesses need different operators.",
      closingSupport: "The principle stays the same: one clear responsibility, the right context and defined limits.",
      cta: "Explore operator solutions",
    },
    operatorProfiles: [
      {
        id: "social",
        number: "01",
        name: "SOCIAL MEDIA OPERATOR",
        availability: "READY-MADE OPERATOR",
        summary: "Keeps your brand present, consistent and moving week after week.",
        visualLabel: "A recurring social media operating cycle from brand context and planning through review, publishing and learning.",
        details: [
          { term: "RESPONSIBILITY", description: "Keep the brand’s social presence active, consistent and aligned with the business." },
          { term: "WATCHES", description: "The content calendar, brand context, upcoming offers, events and approved priorities." },
          { term: "DOES", description: "Plans the weekly content, prepares posts, coordinates review and publishes approved material on schedule." },
          { term: "BRINGS TO YOU", description: "New campaigns, sensitive brand decisions and anything that needs direct founder input." },
        ],
      },
      {
        id: "requests",
        number: "02",
        name: "CUSTOMER REQUEST OPERATOR",
        availability: "CUSTOM OPERATOR",
        summary: "Keeps each incoming request moving toward the right next action.",
        visualLabel: "An incoming customer request moving through context, checks, response and follow-up, with unusual cases escalated to a person.",
        details: [
          { term: "RESPONSIBILITY", description: "Keep incoming customer requests moving from the first message to the right next action." },
          { term: "WATCHES", description: "Messages, website enquiries, customer information, product or service details and previous conversations." },
          { term: "DOES", description: "Understands the request, checks the relevant information, prepares or sends permitted responses, updates the record and follows up when needed." },
          { term: "BRINGS TO YOU", description: "Unusual requests, complaints, special conditions and decisions outside its defined limits." },
        ],
      },
    ],
    socialCycle: [
      { id: "context", label: "BRAND CONTEXT" },
      { id: "plan", label: "WEEKLY PLAN" },
      { id: "create", label: "CREATE" },
      { id: "review", label: "REVIEW", human: true },
      { id: "publish", label: "PUBLISH" },
      { id: "learn", label: "LEARN" },
    ],
    requestFlow: [
      { id: "request", label: "REQUEST" },
      { id: "context", label: "CONTEXT" },
      { id: "check", label: "CHECK" },
      { id: "respond", label: "RESPOND" },
      { id: "follow-up", label: "FOLLOW UP" },
      { id: "complete", label: "COMPLETE" },
    ],
    visuals: {
      social: {
        centerSub: "RECURRING OPERATING CYCLE",
        centerTitle: "SOCIAL\nOPERATOR",
        centerDesc: "Every week continues\nfrom the last",
        humanReview: "HUMAN REVIEW",
      },
      requests: {
        incoming: "NEW REQUEST RECEIVED",
        escalationSub: "OUTSIDE DEFINED LIMITS",
        escalationTitle: "HUMAN DECISION",
        flowOutcome: "REQUEST MOVED TO THE RIGHT NEXT ACTION",
      },
      profileMeta: "OPERATOR PROFILE",
    },
  },
  intake: {
    startWithWorkCopy: {
      eyebrow: "05 — START WITH THE WORK",
      headlineLines: ["You do not need", "to know what", "to build."],
      supportingLead: "Tell us what keeps slowing down, repeating or returning to you.",
      supporting: "We will help identify the right starting point, define the solution and shape the operator around the way your business actually works.",
      promptLabel: "BEGIN WITH A SENTENCE",
      microcopy: "No technical brief required.",
      cta: "Start with your workflow",
      firstSignal: "THE FIRST SIGNAL",
      placeToBegin: "A PLACE TO BEGIN",
    },
    startingSignals: [
      { id: "requests", text: "Every customer request eventually comes back to me." },
      { id: "reporting", text: "Every week we build the report manually from several spreadsheets." },
      { id: "social", text: "Our social channels only move when someone is reminded." },
      { id: "follow-up", text: "Client follow-up is too easy to miss." },
    ],
  },
} as const;
